import { Metadata } from "next";

export const metadata: Metadata = {
  title:{
    absolute: "Blog"
  },
  description: "Generated by create next app",
};
export default function Blog() {
    return (
      <h1>My Blog</h1>
    );
  }